### ISSUE TITLE
Nomenclature da utilizzare

### ISSUE THREAD

**Issue by Giulia2Gargano** [Giulia2Gargano/catalogoProdotto-ill#1]
Il nome dell' [] dentro il dto risposta sarà: **listaProdotti**;
nella richiesta la proprietà di tipo prodotto sarà: **prodotto**;
il nome da assegnare all'entità sarà: **prodotto**;
Per aggiornamenti utilizziamo questo ticket.

**Comment by Emanuele1927** [comment]
Al campo id, abbiamo assegnato bigint

**Comment by Giulia2Gargano** [comment]
url del metodo recupera= http://localhost:8080/recupera

**Comment by Giulia2Gargano** [comment]
url del metodo aggiungi =http://localhost:8080/aggiungi 
url del metodo svuota = http://localhost:8080/svuota
url del metodo elimina = http://localhost:8080/elimina

**Comment by MatteoPalombo99** [comment]
Nomenclatura rispettata, esercizio svolto.
